### ISSUE TITLE
Fix Level 1

### ISSUE THREAD

**Issue by CharlyJazz** [CharlyJazz/Medium-API-Clone#18]
*Add to readme topic endpoints

*Fix endpoint names:

get-users to users
create-user to users
create-topic to topics

Why? https://restfulapi.net/resource-naming/

![image](https://user-images.githubusercontent.com/12489333/96917089-cfd1cc80-147e-11eb-85ab-5f783a61e8de.png)

This mean POST /api/create-resource is redundant because the POST method define the CRUD action to perfome (THE CREATION)

* Unify all response format is a single one:

i founded this format : `return {"response": "All register topics", "topics": all_topics} `

but in other response you have ` return new_post, 201` 

So you need define a unique format for al responses, no matter if the response is a 404 o 201
Some examples of very semantic response formats:

`{status: 200, description: "Products founded", payload: [......]} `

`{payload: [....], metadata: {
    timestamp: A date,
    http_status_code: 200,
    description: "xxxxxx",
    errors: [],
    user_authenticated: user object
}}`

You need choose a format and use is all responses. You can research in internet to find others examples

**Comment by CharlyJazz** [comment]
* You are missing close the tcp connection with the database is some if else sentences

![image](https://user-images.githubusercontent.com/12489333/96918207-5a66fb80-1480-11eb-9a08-b72e00cb36ca.png)

**Comment by JoshieKun** [comment]
#19 here it is lad.

**Comment by CharlyJazz** [comment]
#20
